import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/navbar";
import { BackgroundSvg } from "@/components/ui/background";
import Footer from "@/components/footer/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// bg-[#F5F5F5]
// bg-no-repeat bg-cover bg-[url('/bg.svg')]
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} scroll-smooth bg-white`}>
          <Navbar />
          {children}
          <Footer />
        </body>
    </html>
  );
}
