import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/navbar";
import { BackgroundSvg } from "@/components/ui/background";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// bg-no-repeat bg-cover bg-[url('/bg.svg')]
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-no-repeat bg-cover bg-[url('/bg.svg')]`}>
          <Navbar />
          {children}
        </body>
    </html>
  );
}
